config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]

  root 'welcome#homepage'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  validates :title,
            presence: true,
            on: :create,
            length: { maximum: 30 }

  validates :title,
            presence: true,
            on: :update,
            length: { maximum: 30 }

  validates :body,
            on: :create,
            length: { maximum: 1000 }

  validates :body,
            on: :update,
            length: { maximum: 1000 }

  def validate_and_update(params)
    if params[:title].empty?
      params[:title] = params[:body][0..29]
    end

    return self.update(params)
  end

  def validate_and_save
    return self.save if valid_title?

    set_body_as_title if has_body?
    return self.save
  end

  def valid_title?
    title.size > 0 && title.size < 30
  end

  def has_body?
    body.size > 0
  end

  def set_body_as_title
    self.title = body[0..29]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "Must be logged in to do that"
      redirect_to root_path
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_user
  before_action :set_note, only: [:edit, :update, :destroy]

  def index
    @notes = Note.where(user_id: current_user.id)
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id

    if @note.validate_and_save
      flash[:notice] = "Note created"
      redirect_to notes_path
    else
      flash[:error] = "Note creation failed. See errors below"
      render :new
    end
  end

  def edit; end

  def update
    if @note.validate_and_update(note_params)
      flash[:notice] = "Note updated"
      redirect_to notes_path
    else
      flash[:error] = "Note update failed. See errors below"
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path, flash: { notice: "Note destroyed"}
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.where(email: params[:email]).first

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You have been logged in"
      redirect_to notes_path
    else
      flash[:error] = "There is something wrong with your username or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have successfully logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, flash: { notice: "Welcome #{@user.username}! Log in to begin." }
    else
      flash[:error] = "Account creation failed. See errors for more info"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def homepage; end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_datetime(dt)
    # hard coding this to display for Eastern time. If this was going to be
    # used in an actual live production environment we could use some javascript
    # to ascertain the users timezone so we can set it to their actual local time.
    dt.in_time_zone('Eastern Time (US & Canada)').strftime('%a %I:%M')
  end
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="w-100 alert alert-<%= name == "notice" ? "warning" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
  <h1 class="my-0 mr-md-auto font-weight-bold h3"><%= link_to "My Notes", root_path, class: "text-dark text-decoration-none" %></h1>
  <nav class="my-2 my-md-0 mr-md-3">
    <% if logged_in? %>
      <span>Welcome, <%= current_user.username %></span>
    <% end %>

    <% if logged_in? %>
      <%= link_to "New Note", new_note_path, class: "p-2 text-dark" %>
      <%= link_to "Log Out", logout_path, class: "p-2 text-dark" %>
    <% else %>
      <%= link_to "Signup", signup_path, class: "p-2 text-dark" %>
      <%= link_to "Log In", login_path, class: "p-2 text-dark" %>
    <% end %>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoteManagementSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
      <div id="main" role="main" class="container">
      <div class="row justify-content-center align-items-center flex-column">
        <%= render 'layouts/messages' %>
        <%= yield %>
    <footer>
    </footer>
  </body>
</html>

app/views/notes/_form.html.erb
<%= render 'shared/errors', obj: note %>

<div class="text-center">
  <%= form_with model: note, class: "form-signin", local: true do |f| %>
    <h1 class="h3 mb-3 font-weight-normal"><%= note.new_record? ? 'Create Note' : 'Edit Note' %></h1>
    <%= f.label :title, class: "sr-only" %>
    <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
    <%= f.label :body, class: "sr-only" %>
    <%= f.text_area :body, placeholder: "Body", class: "form-control" %>
    <%= f.submit note.new_record? ? 'Create Note' : 'Update Note', class: "btn btn-lg btn-primary btn-block" %>
  <% end %>
<div>

app/views/notes/_note.html.erb
<div class="rounded bg-white mt-5 shadow text-center p-4">
  <h3 class="font-weight-bold"><%= note.title %><h3>
  <p class="font-weight-light">created by: <%= note.user.username %>, <%= note.created_at.strftime("%a %I:%M") %><p>
  <%= link_to 'Edit Note', edit_note_path(note) %> | <%= link_to 'Delete Note', note, method: :delete, data: { confirm: "Are you sure?" } %>
  <p class="font-weight-regular text-justify"><%= note.body %></p>
<div>

app/views/notes/edit.html.erb
<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<h1>Notes</h1>

<% if @notes.empty? %>
  <p>Oh no! You have no notes! <%= link_to 'click here', new_note_path %> to create your first note.</p>
<% end %>

<ul>
  <% @notes.each do |note| %>
    <li class="list-unstyled">
      <%= render 'note', note: note %>
    </li>
  <% end %>
</ul>

app/views/notes/new.html.erb
<%= render 'form', note: @note %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-warning span8" >
    <h5>There were some errors: </h5>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="text-center">
  <%= form_with model: @user, class: "form-signin", local: true do |f| %>
    <h1 class="h3 mb-3 font-weight-normal">Sign Up</h1>
    <%= f.label :username, class: "sr-only" %>
    <%= f.text_field :username, placeholder: "Username", class: "form-control" %>
    <%= f.label :email, class: "sr-only" %>
    <%= f.text_field :email, placeholder: "Email address", class: "form-control" %>
    <%= f.label :password, class: "sr-only" %>
    <%= f.text_field :password, placeholder: "Password", class: "form-control" %>
    <%= f.submit "Create User", class: "btn btn-lg btn-primary btn-block" %>
  <% end %>
<div>

app/views/welcome/homepage.html.erb
<h1>Welcome!</h1>
<% if current_user %>
  <p><%= current_user.username %></p>
  <p>
    <%= link_to 'visit note dashboard', notes_path %>
  </p>
<% else %>
  <p>
    To use this application please
    <%= link_to 'sign up', login_path %> or
    <%= link_to 'log in', login_path %>
  </p>
<% end %>